---@meta _

---@class PathExpandOptions
---@field base Path|string?
---@field home Path|string|boolean?
---@field expand_base boolean?

---@class (exact) Path
---@field new fun(path: string?): Path
---@field home fun(): Path
---@field is_absolute fun(self): boolean
---@field basename fun(self, suffix: string?): string
---@field dirname fun(self): string
---@field each_parent fun(self, cb: fun(path: Path))
---@field each_part fun(self, cb: fun(str: string))
---@field ends_with_separator fun(self): boolean
---@field expand fun(self, options: PathExpandOptions?): Path
---@field extension fun(self): string
---@field join fun(self, parts: string[]|string): Path
---@field normalize fun(self, remove_final_separator: boolean?): Path
---@field parent fun(self): Path
---@field parents fun(self): Path[]
---@field parts fun(self): string[]
---@field relative_to fun(self, base: Path|string): Path
---@field is_relative_to fun(self, base: Path|string): Path?
---@field root fun(self): Path?
---@field sibling fun(self, name: Path|string): Path
---@field stem fun(self): string
---@field __tostring fun(self): string
---@operator concat(): Path
Path = {}
