name: luajit.cr CI

on:
  push:
    branches: [master]
  pull_request:
    branches: "*"

jobs:
  linux-specs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install LuaJIT
        run: sudo apt-get install luajit-5.1-dev
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Run tests
        run: crystal spec

  windows-specs:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build LuaJIT for Windows
        run: .\scripts\build.ps1
      - name: Run tests
        run: crystal spec
