name: Nightly Example

on:
  push:
    branches: [master]

jobs:
  windows:
    if: "startsWith(github.event.head_commit.message, 'nightly')"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: crystal-lang/install-crystal@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build LuaJIT for Windows
        run: .\scripts\build_luajit.bat
      - name: Compile Binary
        run: |
          crystal build -o example.exe --release example.cr
          $compress = @{
            Path = "example.exe", "example.pdb"
            DestinationPath = "example-nightly-windows-x86_64-msvc.zip"
          }
          Compress-Archive @compress
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: example
          path: |
            example.exe
            example.pdb
            example-nightly-windows-x86_64-msvc.zip

  release:
    needs: windows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - name: Prepare Artifacts
        run: |
          mv artifacts/example/* .
          sha256sum example.exe example.pdb > checksums.txt
      - name: Create Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view nightly &>/dev/null && gh release delete nightly -y
          gh release create nightly -pt Nightly --notes "Nightly release for $(date +%F)."
          gh release upload nightly checksums.txt
          gh release upload nightly example-nightly-windows-x86_64-msvc.zip
